
# Gopkg.toml example
#
# Refer to https://github.com/golang/dep/blob/master/docs/Gopkg.toml.md
# for detailed Gopkg.toml documentation.
#
# required = ["github.com/user/thing/cmd/thing"]
# ignored = ["github.com/user/project/pkgX", "bitbucket.org/user/project/pkgA/pkgY"]
#
# [[constraint]]
#   name = "github.com/user/project"
#   version = "1.0.0"
#
# [[constraint]]
#   name = "github.com/user/project2"
#   branch = "dev"
#   source = "github.com/myfork/project2"
#
# [[override]]
#  name = "github.com/x/y"
#  version = "2.4.0"


[[constraint]]
  name = "github.com/caarlos0/env"
  version = "3.1.1"

[[constraint]]
  branch = "master"
  name = "github.com/gin-gonic/contrib"

[[constraint]]
  name = "github.com/gin-gonic/gin"
  version = "1.2.0"

[[constraint]]
  branch = "master"
  name = "github.com/jinzhu/gorm"
  source = "https://github.com/iReflect/gorm.git"

[[constraint]]
  branch = "master"
  name = "github.com/lib/pq"

[[constraint]]
  branch = "master"
  name = "github.com/pressly/goose"
  source = "https://github.com/iReflect/goose.git"

[[constraint]]
  name = "github.com/qor/admin"
  revision = "431624c143c9bc451659736f71781f3c8264420c"

[[constraint]]
  name = "github.com/qor/qor"
  revision = "610165c4bb100d28fbe93c4bf691a1cab4508201"

[[constraint]]
  name = "github.com/qor/roles"
  revision = "d6375609fe3e5da46ad3a574fae244fb633e79c1"

[[constraint]]
  name = "github.com/sirupsen/logrus"
  version = "1.0.3"
