# Golang CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-go/ for more details
version: 2
jobs:
  build:
    docker:
      - image: circleci/golang:1.9
    working_directory: /go/src/github.com/{{ORG_NAME}}/{{REPO_NAME}}
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-reflect-app-{{ .Revision }}
      - run:
          name: Build artifacts
          command: make all

      - store_artifacts:
          path: .gopath/bin/
          destination: build
  test:
    docker:
      - image: circleci/golang:1.9
        environment:
        - DB_DSN="host=localhost user=ireflect password=1Reflect dbname=ireflect-test sslmode=disable"
        - Driver="postgres"
      - image: postgres:9.5
        environment:
        - POSTGRES_USER=ireflect
        - POSTGRES_PASSWORD=1Reflect
        - POSTGRES_DB=ireflect-test
    working_directory: /go/src/github.com/{{ORG_NAME}}/{{REPO_NAME}}
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: |
            curl -L -s https://github.com/golang/dep/releases/download/v0.3.2/dep-linux-amd64 -o /go/bin/dep && chmod +x /go/bin/dep
            make vendor
      - run:
          name: Test
          command: make test-coverage
      - run:
          name: Code coverage
          command: bash <(curl -s https://codecov.io/bash)  
      - save_cache:
          key: v1-reflect-app-{{ .Revision }}
          paths:
            - .gopath/bin

workflows:
  version: 2
  "test_build":
    jobs:
      - test
      - build:
          requires:
            - test
